### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by robgon-art** [christophmeyer/stylegan2-tf2#1]
Hello, thanks for putting this code on GitHub!
I am checking out the project and I noticed that you haven't added a license file.
Please consider specifying an open-source license, i.e. MIT
Cheers, robgon-art

**Comment by christophmeyer** [comment]
Hi Robert, 
sure, I have added the MIT license. 
Best
Christoph

**Comment by robgon-art** [comment]
Great, thanks!
